name: coffee_house
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  go_router: ^11.1.4
  get: ^4.6.5
  sliver_tools: ^0.2.12
  figma_squircle: ^0.5.3
  cached_network_image: ^3.3.0
  either_dart: ^1.0.0
  flutter_group_list_view: ^1.0.3
  uuid: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.3
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
flutter_assets_generator:
  output_dir: src\shared\assets