///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String coffeeHouse = '.env';
  static const String iconsMinus = 'assets/icons/minus.svg';
  static const String iconsPlus = 'assets/icons/plus.svg';
  static const String imagesErrorImage = 'assets/images/error_image.png';

}
